# Generated by Django 3.2.4 on 2021-06-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20210607_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMaster',
            fields=[
                ('CarID', models.AutoField(primary_key=True, serialize=False)),
                ('CarName', models.CharField(max_length=255)),
                ('OldCust', models.CharField(max_length=255)),
                ('CarModel', models.CharField(max_length=255)),
                ('Mfg', models.DateField(blank=True, null=True)),
                ('BuyPrice', models.CharField(max_length=255)),
                ('SellPrice', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=0)),
                ('IsDelete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('CustID', models.AutoField(primary_key=True, serialize=False)),
                ('CustName', models.CharField(max_length=255)),
                ('CustEmail', models.EmailField(max_length=255, unique=True)),
                ('CustAddress', models.CharField(blank=True, max_length=255)),
                ('CustMobile', models.BigIntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=0)),
                ('IsDelete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LeadMaster',
            fields=[
                ('LeadID', models.AutoField(primary_key=True, serialize=False)),
                ('Choices', models.CharField(choices=[('ALTO', 'ALTO'), ('Baleno', 'Baleno'), ('Breeza', 'Breeza')], max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=0)),
                ('IsDelete', models.BooleanField(default=0)),
                ('CustID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customermaster')),
            ],
        ),
    ]
