# Generated by Django 3.2.4 on 2021-06-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_carmaster_customermaster_leadmaster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarMaster',
            new_name='InventoryMaster',
        ),
    ]
