# Generated by Django 3.2.4 on 2021-06-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_carmaster_inventorymaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmaster',
            name='Choices',
        ),
        migrations.AddField(
            model_name='leadmaster',
            name='Choice1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadmaster',
            name='Choice2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadmaster',
            name='Choice3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadmaster',
            name='Choice4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadmaster',
            name='Choice5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadmaster',
            name='Choice6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
