# Generated by Django 3.2.4 on 2021-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210607_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaster',
            name='Doc1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='Engine',
            field=models.CharField(default='KW01', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='KWNo',
            field=models.CharField(default='KW01', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='Milage',
            field=models.CharField(default='KW01', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='RegNo',
            field=models.CharField(default='KW01', max_length=255),
        ),
    ]
