# Generated by Django 3.2.4 on 2021-06-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210609_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDocMaster',
            fields=[
                ('CarDocID', models.AutoField(primary_key=True, serialize=False)),
                ('Doc', models.FileField(max_length=255, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventorymaster',
            name='Doc1',
        ),
    ]
