# Generated by Django 3.2.4 on 2021-06-09 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210609_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardocmaster',
            name='CarID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.inventorymaster'),
        ),
    ]
