# Generated by Django 3.2.4 on 2021-06-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cardocmaster_carid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardocmaster',
            name='DocDescription',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='CarImage',
            field=models.ImageField(default='NULL', max_length=255, upload_to=''),
        ),
    ]
