# Generated by Django 3.2.4 on 2021-06-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210609_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmaster',
            name='CustID',
        ),
        migrations.DeleteModel(
            name='CustomerMaster',
        ),
        migrations.DeleteModel(
            name='LeadMaster',
        ),
    ]
