# Generated by Django 3.2.4 on 2021-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210609_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadMaster',
            fields=[
                ('CustID', models.AutoField(primary_key=True, serialize=False)),
                ('CustName', models.CharField(max_length=255)),
                ('CustEmail', models.EmailField(max_length=255, unique=True)),
                ('CustAddress', models.CharField(blank=True, max_length=255)),
                ('CustMobile', models.BigIntegerField()),
                ('Choices', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=0)),
                ('IsDelete', models.BooleanField(default=0)),
            ],
        ),
    ]
