# Generated by Django 3.2.4 on 2021-06-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_leadmaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadmaster',
            old_name='CustID',
            new_name='LeadID',
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('CustID', models.AutoField(primary_key=True, serialize=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=0)),
                ('IsDelete', models.BooleanField(default=0)),
                ('LeadID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.leadmaster')),
            ],
        ),
    ]
