# Generated by Django 3.2.4 on 2021-06-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210609_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadmaster',
            old_name='CustAddress',
            new_name='LeadAddress',
        ),
        migrations.RenameField(
            model_name='leadmaster',
            old_name='CustEmail',
            new_name='LeadEmail',
        ),
        migrations.RenameField(
            model_name='leadmaster',
            old_name='CustMobile',
            new_name='LeadMobile',
        ),
        migrations.RenameField(
            model_name='leadmaster',
            old_name='CustName',
            new_name='LeadName',
        ),
    ]
