# Generated by Django 3.2.4 on 2021-06-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210609_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerMaster',
        ),
    ]
