# Generated by Django 3.2.4 on 2021-06-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_customermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('CustID', models.AutoField(primary_key=True, serialize=False)),
                ('CustName', models.CharField(max_length=255)),
                ('CustEmail', models.EmailField(max_length=255, unique=True)),
                ('CustMobile', models.BigIntegerField()),
                ('PurchasedCar', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=0)),
                ('IsDelete', models.BooleanField(default=0)),
                ('LeadID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.leadmaster')),
            ],
        ),
    ]
