# Generated by Django 3.2.4 on 2021-06-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_customermaster_leadid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenceMaster',
            fields=[
                ('ExpenceID', models.AutoField(primary_key=True, serialize=False)),
                ('BodyShop_Amount', models.CharField(max_length=20)),
                ('BodyShop_Details', models.CharField(max_length=255)),
                ('Mechanic_Amount', models.CharField(max_length=20)),
                ('Mechanic_Details', models.CharField(max_length=255)),
                ('MOT_Amount', models.CharField(max_length=20)),
                ('MOT_Details', models.CharField(max_length=255)),
                ('Travelling_Amount', models.CharField(max_length=20)),
                ('Travelling_Details', models.CharField(max_length=255)),
                ('Fuel_Amount', models.CharField(max_length=20)),
                ('Fuel_Details', models.CharField(max_length=255)),
                ('Total_Expenses', models.CharField(max_length=20, null=True)),
                ('CarID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.inventorymaster')),
            ],
        ),
    ]
