# Generated by Django 3.2.4 on 2021-06-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_leadmaster_offerprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='CustEmail',
            field=models.EmailField(max_length=255),
        ),
    ]
