# Generated by Django 3.2.4 on 2021-06-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_customermaster_custemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('AdminEmail', models.EmailField(max_length=255, unique=True)),
                ('AdminPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
