# Generated by Django 3.2.4 on 2021-06-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_leadmaster_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaster',
            name='Mfg',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
