# Generated by Django 3.2.4 on 2021-06-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_inventorymaster_mfg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaster',
            name='Mfg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
