# Generated by Django 3.2.4 on 2021-06-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_expencemaster_carregno'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmaster',
            name='AdminUsername',
            field=models.CharField(default='Admin', max_length=255),
        ),
    ]
