# Generated by Django 3.2.4 on 2021-06-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_adminmaster_adminusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmaster',
            name='Comment',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
