# Generated by Django 3.2.4 on 2021-06-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_leadmaster_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmaster',
            name='LeadAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
