# Generated by Django 3.2.4 on 2021-06-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_leadmaster_leadaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaster',
            name='Amount',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
