# Generated by Django 3.2.4 on 2021-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_customermaster_custaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldCarsMaster',
            fields=[
                ('SoldID', models.AutoField(primary_key=True, serialize=False)),
                ('CarName', models.CharField(max_length=255)),
                ('OldCust', models.CharField(max_length=255)),
                ('CarModel', models.CharField(max_length=255)),
                ('Mfg', models.DateField(blank=True, null=True)),
                ('BuyPrice', models.CharField(max_length=255)),
                ('SellPrice', models.CharField(max_length=255)),
                ('CarImage', models.ImageField(default='NULL', max_length=255, upload_to='')),
                ('KWNo', models.CharField(default='KW01', max_length=255)),
                ('RegNo', models.CharField(default='KW01', max_length=255)),
                ('Milage', models.CharField(default='KW01', max_length=255)),
                ('Engine', models.CharField(default='KW01', max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=0)),
                ('IsDelete', models.BooleanField(default=0)),
            ],
        ),
    ]
