# Generated by Django 3.2.4 on 2021-06-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_soldcarsmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldcarsmaster',
            name='CurrentCust',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
