# Generated by Django 3.2.4 on 2021-06-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_soldcarsmaster_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldcarsmaster',
            name='Total_Expenses',
            field=models.CharField(default='NULL', max_length=20, null=True),
        ),
    ]
