# Generated by Django 3.2.4 on 2021-06-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_soldcarsmaster_buy_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldcarsmaster',
            name='Profit',
            field=models.CharField(default='NULL', max_length=20, null=True),
        ),
    ]
