# Generated by Django 3.2.4 on 2021-06-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_soldcarsmaster_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaster',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expencemaster',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadmaster',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldcarsmaster',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
