# Generated by Django 3.2.4 on 2021-06-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210624_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaster',
            name='FinalPrice',
            field=models.CharField(default='00', max_length=255),
        ),
    ]
