# Generated by Django 3.2.4 on 2021-06-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_inventorymaster_finalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaster',
            name='CarImage',
            field=models.ImageField(default='NULL', max_length=255, null=True, upload_to=''),
        ),
    ]
