# Generated by Django 3.2.4 on 2021-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_inventorymaster_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmaster',
            name='LeadEmail',
            field=models.EmailField(max_length=255),
        ),
    ]
