# Generated by Django 3.2.4 on 2021-06-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20210625_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardocmaster',
            name='RegNo',
            field=models.CharField(default='KW01', max_length=255),
        ),
    ]
