# Generated by Django 3.2.4 on 2021-06-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_cardocmaster_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardocmaster',
            name='CarName',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.DeleteModel(
            name='ExpenceMaster',
        ),
    ]
