# Generated by Django 3.2.4 on 2021-06-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_inventorymaster_mfg'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadgerMaster',
            fields=[
                ('LedgerID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(blank=True, null=True)),
                ('CarName', models.CharField(max_length=255)),
                ('RegNo', models.CharField(default='KW01', max_length=255)),
                ('KWNo', models.CharField(default='KW01', max_length=255)),
                ('FinalPrice', models.CharField(default='00', max_length=255)),
                ('Amount', models.CharField(max_length=255)),
                ('Vtype', models.CharField(default='KW01', max_length=255)),
            ],
        ),
    ]
