# Generated by Django 3.2.4 on 2021-06-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_leadgermaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgermaster',
            name='Amount',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='leadgermaster',
            name='FinalPrice',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
