# Generated by Django 3.2.4 on 2021-07-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20210629_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarName', models.CharField(max_length=255)),
                ('CarModel', models.CharField(max_length=255)),
                ('KWNo', models.CharField(default='KW01', max_length=255)),
                ('RegNo', models.CharField(default='KW01', max_length=255)),
                ('Date', models.DateField(blank=True, null=True)),
                ('BodyShop_Amount', models.CharField(default='NULL', max_length=20)),
                ('Mechanic_Amount', models.CharField(default='NULL', max_length=20)),
                ('MOT_Amount', models.CharField(default='NULL', max_length=20)),
                ('Travelling_Amount', models.CharField(default='NULL', max_length=20)),
                ('Fuel_Amount', models.CharField(default='NULL', max_length=20)),
                ('Total_Expenses', models.CharField(default='NULL', max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customermaster',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='customermaster',
            name='OfferPrice',
        ),
        migrations.AddField(
            model_name='customermaster',
            name='DepositeValue',
            field=models.IntegerField(default='00'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='PaidValue',
            field=models.IntegerField(default='00'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='PaymentReciept',
            field=models.FileField(default='NULL', max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='Amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='CustMobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='BodyShop_Amount',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='BuyPrice',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='FinalPrice',
            field=models.CharField(default='00', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='Fuel_Amount',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='MOT_Amount',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='Mechanic_Amount',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='Milage',
            field=models.CharField(default='KW01', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='SellPrice',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='Total_Expenses',
            field=models.CharField(default='NULL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='Travelling_Amount',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadgermaster',
            name='Amount',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='leadgermaster',
            name='FinalPrice',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='leadmaster',
            name='OfferPrice',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AlterField(
            model_name='soldcarsmaster',
            name='Amount',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AlterField(
            model_name='soldcarsmaster',
            name='BuyPrice',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='soldcarsmaster',
            name='Buy_EXP',
            field=models.CharField(default='NULL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='soldcarsmaster',
            name='Milage',
            field=models.CharField(default='KW01', max_length=255),
        ),
        migrations.AlterField(
            model_name='soldcarsmaster',
            name='Profit',
            field=models.CharField(default='NULL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='soldcarsmaster',
            name='SellPrice',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='soldcarsmaster',
            name='Total_Expenses',
            field=models.CharField(default='NULL', max_length=20, null=True),
        ),
    ]
