# Generated by Django 3.2.4 on 2021-07-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20210702_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaster',
            name='Total_Expenses',
            field=models.IntegerField(null=True),
        ),
    ]
